Universe = vanilla
Executable = /gluster/home/ofrebato/baler/run_script.sh
Arguments =
transfer_input_files = /gluster/home/ofrebato/baler/pyproject.toml, /gluster/home/ofrebato/.cache/pypoetry/virtualenvs/baler-O7HYjMIZ-py3.9/bin/activate, /gluster/home/ofrebato/.cache/pypoetry/virtualenvs/baler-O7HYjMIZ-py3.9/bin/python3, /gluster/home/ofrebato/baler/workspaces/MNIST/data/mnist_combined.npz, /gluster/home/ofrebato/baler/workspaces/MNIST/MNIST_project/config/MNIST_project_config.py
transfer_output_files = /gluster/home/ofrebato/baler/run_script.sh, /gluster/home/ofrebato/baler/job.out, /gluster/home/ofrebato/baler/job.err, /gluster/home/ofrebato/baler/job.log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
Log = /gluster/home/ofrebato/baler/job.log
Output = /gluster/home/ofrebato/baler/job.out
Error = /gluster/home/ofrebato/baler/job.err
request_cpus=4
request_disk = 6000000
request_memory = 13000
Queue