name: Docker Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Build Docker image"
        run: |
          env ARCH=${{ env.ARCH }} ./bin/build_docker.sh

      - name: "Run Docker tests"
        run: |
          env ARCH=${{ env.ARCH }} ./bin/test_docker.sh
