name: Code-Quality

on: [pull_request, workflow_dispatch]

jobs:
  test_and_lint:
    strategy:
        fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3

    - name: "install poetry"
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.3.2

    - name: "install dependencies"
      run: poetry install

    - name: "set python path"
      run: echo "PYTHONPATH=.:baler" >> $GITHUB_ENV
    - name: "run syntax check"
      run: |
        ./bin/syntax.sh

    - name: "run tests"
      run: |
        ./bin/tests.sh
